### ISSUE TITLE
Token

### ISSUE THREAD

**Issue by kamish4dow** [zweed4u/HQ#1]
how do I find token
{
    "error": "Auth not valid",
    "errorCode": 105
}

**Comment by zweed4u** [comment]
@kamish4dow just pushed a [commit](https://github.com/zweed4u/HQ/commit/f8371e6b569866625110f77e059f4a06a00cb571) that added sms verification. remove the line in the config that asks you to specify token and add you phone number to the new section (10 numbers no spaces or dashes). This will send you an sms code which you will need to manually enter.

**Comment by kamish4dow** [comment]
https://gyazo.com/afd1a0add16a8d0bc5f55608b6b74d50

**Comment by zweed4u** [comment]
@kamish4dow could add a print statement right before it print the 'verification_response' ?
the only other thing I could think of is the way you're putting your number in the config. it prepends '+1' to your 10 digit number as this is what is expected in the json POSTed
