### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by AyJavasProcessing** [zweed4u/HQ#2]
After clicking it the window crashes. Are there some instructions to running this? Thanks

**Comment by zweed4u** [comment]
You're going to have to be more specific than that.

Adjust the config as needed and resave as config.cfg.
Adjust method used at the bottom of the script to see desired info displayed.
Run from a terminal with python3.

This serves as an API wrapper for use of developers

**Comment by AyJavasProcessing** [comment]
I see. Im able to run it now, but I guess its only for developers use.

**Comment by zweed4u** [comment]
@AyJavasProcessing what are you aiming to do? Check out various methods to see if they suit your needs. I have something locally that actually opens the socket if that's what you're seeking.

**Comment by AyJavasProcessing** [comment]
Oh I was mistaken and thought this would help with searching hq questions.

**Comment by zweed4u** [comment]
@AyJavasProcessing attempt to read the source code before opening frivolous issues please
